@startuml 

title Webserver Design / RTOS Tasks

package Webserver_Package
{
    class Main {}
    note right of Main
        Creates all objects (DI)
    end note

    class DmxControllerWebserver <<RtosTask>> {}

    class Website <<LittleFS>>

    class DmxControllerHttpTask <<RtosTask>> {}
    class PresetsTask <<RtosTask>> {}

    Main *--> DmxControllerWebserver
    
    Website <--> DmxControllerHttpTask : REST API
}

package Common 
{
    package RtosTasks
    {
        class RtosTask <<RtosTask>> {}

        class NodeTask <<RtosTask>> {}
        class HttpTask <<RtosTask>> {}
        note bottom of HttpTask
            Only for
            webservers
            and remotes
        end note        
        class WifiTask <<RtosTask>> {}
        class EspNowTask <<RtosTask>> {}
        class OtaTask <<RtosTask>> {}
        class StatusTask <<RtosTask>> {}
        class NvsTask <<RtosTask>> {}

        NodeTask -u-|> RtosTask
        HttpTask -u-|> RtosTask
        WifiTask -u-|> RtosTask
        EspNowTask -u-|> RtosTask
        OtaTask -u-|> RtosTask
        StatusTask -u-|> RtosTask
        NvsTask -u-|> RtosTask
        
    }
    package ESP
    {
        class IEspWifi <<ESP32>> {}
        class IEspNow <<ESP32>> {}
        class IEspNvs <<ESP32>> {}
    }

    StatusTask ---> IEspNow
    WifiTask ---> IEspWifi
    EspNowTask ---> IEspNow
    NvsTask ---> IEspNvs
}

DmxControllerWebserver --|> NodeTask
DmxControllerHttpTask --|> HttpTask
PresetsTask --|> RtosTask

DmxControllerWebserver *-- DmxControllerHttpTask
DmxControllerWebserver *-- PresetsTask
DmxControllerWebserver *-- StatusTask
DmxControllerWebserver *-- EspNowTask
DmxControllerWebserver *-- WifiTask
DmxControllerWebserver *-- OtaTask
DmxControllerWebserver *-- NvsTask

@enduml

@startuml 

title Webserver Design / API Endpoints, example of security API endpoint 

package Webserver_Package
{
    class Main {}

    class DmxControllerWebserver <<RtosTask>> {}

    class Website <<LittleFS>>

    class DmxControllerHttpTask <<RtosTask>> {}
    class PresetsTask <<RtosTask>> {}

    Main *--> DmxControllerWebserver
    Main *--> DmxControllerHttpTask
    Main *--> PresetsTask

    Website --> DmxControllerHttpTask : 1. POST Esp Now Key
}

package Common 
{
    package Apis 
    {
        class ApiSecurity <<API>> {}
        class ApiFirmware <<API>> {}
        class ApiLogging <<API>> {}
        class ApiNodes <<API>> {}
        class ApiResposne <<API>> {}
        class ApiStatus <<API>> {}
        class ApiSystem <<API>> {}
        class ApiValidator <<API>> {}
        class StaticFileHandler <<API>> {}
    }

    package RtosTasks
    {
        class RtosTask <<RtosTask>> {}

        class NodeTask <<RtosTask>> {}
        class HttpTask <<RtosTask>> {}
        class ApiServer {}
        HttpTask --> ApiServer : 2b Handle by API Server

        note right of HttpTask
            Only for
            webservers
            and remotes
        end note        
        class WifiTask <<RtosTask>> {}
        class EspNowTask <<RtosTask>> {}
        class OtaTask <<RtosTask>> {}
        class StatusTask <<RtosTask>> {}
        class NvsTask <<RtosTask>> {}

        NodeTask -u-|> RtosTask
        HttpTask -u-|> RtosTask
        WifiTask -u-|> RtosTask
        EspNowTask -u-|> RtosTask
        OtaTask -u-|> RtosTask
        StatusTask -u-|> RtosTask
        NvsTask -u-|> RtosTask
    }

    ApiServer --> ApiSecurity : 3. Esp Now Key is for security
    ApiSecurity -> NodeTask : 4. Handle Esp Now key
    NodeTask --> EspNowTask : 5. Send to other nodes (for all nodes)
    EspNowTask ..> NodeTask: 5b Ack
    NodeTask --> NvsTask : 6. Store in NVS 
    NvsTask ..> NodeTask : 6b. Ack
    NodeTask --> HttpTask : 7. Respond to HTTP request
}

DmxControllerWebserver --|> NodeTask
DmxControllerHttpTask --> HttpTask : 2. (Common API)
PresetsTask --|> RtosTask

@enduml

@startuml 

title Webserver Design / API Endpoints, example of security API endpoint (as seq diagram)

participant Website
participant DmxControllerHttpTask
participant HttpTask
participant ApiServer
participant ApiSecurity
participant NodeTask
participant EspNowTask
participant NvsTask

Website ->  DmxControllerHttpTask : POST Esp Now Key
DmxControllerHttpTask -> HttpTask : (Common API handler)
HttpTask -> ApiServer : Delegate to API Server
ApiServer -> ApiSecurity : Esp Now Key \n is for security
ApiSecurity -> NodeTask : Handle Esp Now key
NodeTask -> EspNowTask : Send to other nodes \n (for all nodes)
EspNowTask --> IEspNow : Send Esp Now message
IEspNow --> EspNowTask : Ack
EspNowTask --> NodeTask: Ack
NodeTask -> NvsTask : Store in NVS
NvsTask --> IEspNvs: Store in NVS
IEspNvs --> NvsTask: Ack
NvsTask --> NodeTask : Ack
NodeTask --> NodeTask : Wait for acks from EspNowTask and NvsTask
NodeTask --> ApiSecurity : Ack
ApiSecurity --> ApiServer : Ack
ApiServer --> HttpTask : Ack
HttpTask --> DmxControllerHttpTask : Respond to \n HTTP request
DmxControllerHttpTask --> Website : Respond to \n HTTP request

@enduml 

@startuml 

title Webserver Design / DMX Controller, Get preset

participant Website
participant DmxControllerTask
participant DmxControllerHttpTask
participant ApiPreset
participant PresetTask
participant ESP32LittleFs

Website -> DmxControllerHttpTask : GET preset
DmxControllerHttpTask -> ApiPreset : parseRequest()
ApiPreset --> DmxControllerHttpTask : presetId
DmxControllerHttpTask -> PresetTask : getPreset(presetId)
PresetTask -> ESP32LittleFs : readPresetFile(presetId)
PresetTask --> PresetTask : wait for data
PresetTask -> DmxControllerTask : sendPresetData(data)
DmxControllerTask -> ApiPreset : formatResponse(data)
ApiPreset --> DmxControllerTask : response
DmxControllerTask -> DmxControllerHttpTask : response
DmxControllerHttpTask -> Website : HTTP response

@enduml

@startuml 

title Webserver Design / ESP32 Interfaces

package Common_Package
{
    package RtosTasks_Package
    {
        class RtosTask <<RtosTask>> {}

        class NodeTask <<RtosTask>> {}
        class HttpTask <<RtosTask>> {}
        note bottom of HttpTask
            Only for
            webservers 
            and remotes
        end note        
        class WifiTask <<RtosTask>> {}
        class EspNowTask <<RtosTask>> {}
        class OtaTask <<RtosTask>> {}
        class StatusTask <<RtosTask>> {}
        class NvsTask <<RtosTask>> {}

        NodeTask -u-|> RtosTask
        HttpTask -u-|> RtosTask
        WifiTask -u-|> RtosTask
        EspNowTask -u-|> RtosTask
        OtaTask -u-|> RtosTask
        StatusTask -u-|> RtosTask
        NvsTask -u-|> RtosTask
        
    }

    package ESP32_Package
    {
        package EspFileSystems_Package     
        {
            class IEspLittleFs <<ESP32>> {}
            class EspLittleFs <<ESP32>> {}
            class MockEspLittleFs <<ESP32>> {}
            class esp_littlfs_if_h <<C>> {}
            class esp_spiffs_if_h <<C>> {}

            EspLittleFs -u-|> IEspLittleFs
            MockEspLittleFs -u-|> IEspLittleFs
            note bottom of MockEspLittleFs
                Only for testing
            end note
            EspLittleFs --> esp_littlfs_if_h
            EspLittleFs --> esp_spiffs_if_h
        }

        package IEspWifi_Package
        {

        }
        
        package IEspNow_Package
        {
            class IEspNow <<ESP32>> {}
            class EspNow <<ESP32>> {}   
            class MockEspNow <<ESP32>> {}

            EspNow -u-|> IEspNow
            MockEspNow -u-|> IEspNow
            note bottom of MockEspNow
                Only for testing
            end note

            EspNow --> esp_now_if_h
        }

        package IEspNvs_Package 
        {
            class IEspNvs <<ESP32>> {}
            class EspNvs <<ESP32>> {}
            class MockEspNvs <<ESP32>> {}

            EspNvs -u-|> IEspNvs
            MockEspNvs -u-|> IEspNvs
            note bottom of MockEspNvs
                Only for testing
            end note

            EspNvs --> nvs_if_h
        }

        package IEspHttpServer_Package
        {
            class IEspHttpServer <<ESP32>> {}
            class EspHttpServer <<ESP32>> {}    
            class MockEspHttpServer <<ESP32>> {}

            EspHttpServer -u-|> IEspHttpServer
            MockEspHttpServer -u-|> IEspHttpServer
            note bottom of MockEspHttpServer
                Only for testing
            end note

            EspHttpServer --> esp_http_server_if_h
        }

        package IEspLogger_Package
        {
            class IEspLogger <<ESP32>> {}
            class EspLogger <<ESP32>> {}
            class MockEspLogger <<ESP32>> {}

            EspLogger -u-|> IEspLogger
            MockEspLogger -u-|> IEspLogger
            note bottom of MockEspLogger
                Only for testing
            end note

            EspLogger --> esp_logger_if_h
        }


    }

    ESP32_Package -[hidden]u-----> RtosTasks_Package 

    NodeTask --> IEspLogger
    HttpTask --> IEspLogger
    WifiTask --> IEspLogger
    EspNowTask --> IEspLogger
    OtaTask --> IEspLogger
    StatusTask --> IEspLogger
    NvsTask --> IEspLogger

    StatusTask --> IEspNow
    'WifiTask --> IEspWifi
    HttpTask ---> IEspHttpServer
    EspNowTask --> IEspNow
    NvsTask --> IEspNvs
}

@enduml
